name: 构建

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package_variant: [ apt-android-7]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
        - name: 1 java配置
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: 2 克隆仓库
      uses: actions/checkout@v4
    - name: 构建
      run: chmod +x ./gradlew && ./gradlew assembleDebug
    - name: Store generated universal APK file
      uses: actions/upload-artifact@v4
      with:
        name: termux-app-universal
        path: |
            ./app/build/outputs/apk/debug/termux-app-universal-debug.apk
            ./app/build/outputs/apk/debug/output-metadata.json
